export const imagenes = {
    acuario:{
        acuarioCarousel: [
            'https://i.postimg.cc/Y2zy1c16/img0.jpg',
            'https://i.postimg.cc/W4Z5zxNJ/img1.jpg',
            'https://i.postimg.cc/CxBNr9f6/img6.jpg',
            'https://i.postimg.cc/C1HJHDfh/img5.jpg',
            'https://i.postimg.cc/90Lpshps/img10.jpg',
            'https://i.postimg.cc/8k4t7RSw-/img11.jpg',
            'https://i.postimg.cc/kGJsj4xx/img9.jpg',
            'https://i.postimg.cc/Dw8jk8R6/img2.jpg',
            'https://i.postimg.cc/pTtqFkrc/img3.jpg',
            'https://i.postimg.cc/GmVMcbCC/img4.jpg',
            'https://i.postimg.cc/X72Hzw1X/img7.jpg'
        ],
        acuarioGaleria: []
    },
    alma:{
        almaCarousel:[
            'https://i.postimg.cc/nrJsqFsB/img1.jpg',
            'https://i.postimg.cc/25gL8FrH/img2.jpg',
            'https://i.postimg.cc/Wb7Z6kw3/img3.jpg',
            'https://i.postimg.cc/8C7rSnQJ/img4.jpg',
            'https://i.postimg.cc/zGXgdGxk/img5.jpg',
            'https://i.postimg.cc/RZN066P2/img6.jpg',
            'https://i.postimg.cc/vZkZWYkT/img7.jpg',
            'https://i.postimg.cc/Vsq0mCTR/img8.jpg',
            'https://i.postimg.cc/nhRQNf5f/img9.jpg',
        ],
        almaGaleria:[]
    },
    bosque:{
        bosqueCarousel:[
            'https://i.postimg.cc/wBX0hvMQ/img1.jpg',
            'https://i.postimg.cc/y6vpQkPf/img2.jpg',
            'https://i.postimg.cc/sDL6zqb7/img3.jpg',
            'https://i.postimg.cc/TY17ZfNT/img4.jpg',
            'https://i.postimg.cc/ZqtwB3bq/img5.jpg',
            'https://i.postimg.cc/0yJtyZq3/img6.jpg',
            'https://i.postimg.cc/G2zK55kB/img7.jpg '
        ],
        bosqueGalery:[]
    },
    refugio:{
        refugioCarousel:[
            'https://i.postimg.cc/nhjdLxmp/img1.jpg',
            'https://i.postimg.cc/htk2zY8x/img2.jpg',
            'https://i.postimg.cc/YSQb1x8P/img3.jpg'
        ],
        refugioGalery:[]
    }
}